In [2]:
import numpy as np 
import pandas as pd

In [3]:
from sklearn.preprocessing import  OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv("covid.csv")

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['fever'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: fever
Non-Null Count  Dtype  
--------------  -----  
90 non-null     float64
dtypes: float64(1)
memory usage: 928.0 bytes


In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=0)

In [8]:
Sim = SimpleImputer()

X_train_fever = Sim.fit_transform(X_train[['fever']])

X_test_fevet = Sim.fit_transform(X_test[['fever']])

In [9]:
Or = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = Or.fit_transform(X_train[['cough']])

X_test_cough = Or.fit_transform(X_test[['cough']])

In [10]:
ON = OneHotEncoder(drop='first',sparse=False)

X_train_gender_city = ON.fit_transform(X_train[['gender','city']]) 

X_test_gender_city = ON.fit_transform(X_test[['gender','city']])



In [11]:
X_train_age = X_train.drop(columns=['gender','cough','city','fever']).values
X_train_age.shape

X_test_age = X_test.drop(columns=['gender','cough','city','fever']).values

type(X_test_age)

numpy.ndarray

In [12]:
X_train_transfromed = np.concatenate((X_train_age,X_train_gender_city,X_train_cough,X_train_fever),axis=1)

X_test_transfromed = np.concatenate((X_test_age,X_test_gender_city,X_test_cough,X_test_fevet),axis=1)

In [13]:
X_test_transfromed

array([[ 19.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        , 100.        ],
       [ 25.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        , 104.        ],
       [ 42.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        , 101.        ],
       [ 81.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        , 101.        ],
       [  5.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        , 102.        ],
       [ 27.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        , 100.        ],
       [ 69.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        , 103.        ],
       [ 34.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  98.        ],
       [ 60.        ,   0.        ,   0.        ,   0.        ,
          1.    

In [14]:
from sklearn.compose import ColumnTransformer

Transfromed = ColumnTransformer(transformers=[
    ('tfn1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse=False),['gender','city'])
],remainder='passthrough')

In [15]:
Transfromed.fit_transform(X_train)
Transfromed.fit_transform(X_test)

array([[100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

# Nest p

In [16]:
import numpy as np
import pandas as pd

In [17]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute  import SimpleImputer

In [18]:
df = pd.read_csv("aug_test.csv")

In [19]:
df.sample(5)

enrollee_id      city  city_development_index  gender  \
625         13230  city_103                   0.920  Female   
2010        25713  city_136                   0.897    Male   
1113        24293   city_21                   0.624  Female   
1047        10640  city_116                   0.743     NaN   
1606        31465   city_16                   0.910    Male   

          relevent_experience enrolled_university education_level  \
625   Has relevent experience       no_enrollment        Graduate   
2010  Has relevent experience       no_enrollment        Graduate   
1113  Has relevent experience    Full time course        Graduate   
1047  Has relevent experience       no_enrollment         Masters   
1606  Has relevent experience       no_enrollment         Masters   

     major_discipline experience company_size company_type last_new_job  \
625              STEM          5          NaN          NaN            1   
2010             STEM         18    1000-4999      Pvt Ltd            3   
1113             STEM         <1        50-99      Pvt Ltd            1   
1047             STEM         13      100-500          NGO            1   
1606             STEM        >20       10000+      Pvt Ltd           >4   

      training_hours  
625               29  
2010              73  
1113              49  
1047             166  
1606              53

In [20]:
df = df[['gender','relevent_experience','enrolled_university','education_level']]

In [21]:
df.sample(5)

gender      relevent_experience enrolled_university education_level
528    Male   No relevent experience    Full time course        Graduate
2085   Male  Has relevent experience       no_enrollment        Graduate
670     NaN   No relevent experience    Part time course        Graduate
1717    NaN  Has relevent experience    Full time course        Graduate
455    Male  Has relevent experience    Full time course        Graduate

In [22]:
df = df.dropna()
df.sample(5)

gender      relevent_experience enrolled_university education_level
187    Male  Has relevent experience       no_enrollment        Graduate
1757   Male  Has relevent experience       no_enrollment        Graduate
1509   Male   No relevent experience    Full time course     High School
559    Male  Has relevent experience    Full time course         Masters
999    Male  Has relevent experience       no_enrollment        Graduate

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['enrolled_university']),df['enrolled_university'],test_size=0.2,random_state=0)

In [24]:
len(X_train),len(X_test),len(y_train),len(y_test)

(1264, 316, 1264, 316)

In [25]:
OH = OneHotEncoder(sparse=False)

X_train_gender_relevent_experience = OH.fit_transform(X_train[['gender','relevent_experience']])

X_test_gender_relevent_experience = OH.fit_transform(X_test[['gender','relevent_experience']])


In [26]:
X_train_gender_relevent_experience


array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [27]:
y_train.head(5)

869     Part time course
76         no_enrollment
1674       no_enrollment
1573       no_enrollment
1217       no_enrollment
Name: enrolled_university, dtype: object

In [28]:
Or = OrdinalEncoder(categories=[['Primary School','High School','Graduate','Masters','Phd']])

X_train_education_level = Or.fit_transform(X_train[['education_level']])

X_test_education_level = Or.fit_transform(X_test[['education_level']])


In [29]:
from sklearn.preprocessing import LabelEncoder

Le = LabelEncoder()

y_train = Le.fit_transform(y_train)
y_test = Le.fit_transform(y_test)


In [30]:
y_train.shape

(1264,)

In [31]:
X_train_transfromed = np.concatenate((X_train_gender_relevent_experience,X_train_education_level),axis=1)

X_test_transfromed = np.concatenate((X_test_gender_relevent_experience,X_test_education_level),axis=1)

In [32]:
X_test_transfromed

array([[0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 1., 2.],
       [0., 1., 0., 1., 0., 2.],
       ...,
       [1., 0., 0., 1., 0., 2.],
       [1., 0., 0., 0., 1., 2.],
       [0., 1., 0., 0., 1., 2.]])

In [33]:
from sklearn.compose import ColumnTransformer

Transfromed = ColumnTransformer(transformers=[
    ('tfn1',OrdinalEncoder(categories=[['Primary School','High School','Graduate','Masters','Phd']]),['education_level']),
    ('tfn2',OneHotEncoder(drop='first',sparse=False),['gender','relevent_experience'])
],remainder='passthrough')

In [34]:
Transfromed.fit_transform(X_train)

array([[2., 1., 0., 0.],
       [2., 1., 0., 0.],
       [2., 1., 0., 0.],
       ...,
       [3., 0., 0., 1.],
       [2., 1., 0., 0.],
       [2., 1., 0., 0.]])